#f=open("MY File.txt","x")
#fr=open("MY File.txt","a")
#content=fr.append("x-> creates a file")
#print(content)
f=open("File.txt","a+")
f.write("Welcome to Kanagudur")
f.seek(0)
data=f.read()
print(f.tell())
print(data)
